# Description
#   Floods the screen with lorem ipsum to hide NSFW content
#
# Dependencies:
#   None
#
# Configuration:
#   None
#
# Commands:
#   If it even hears NSFW it will scream
#
# Author:
#   Eric Lui

module.exports = (robot) ->
  robot.hear /NSFW/i, (msg) ->
    msg.send "Cat ipsum dolor sit amet, why must they do that intently sniff hand. Sleep on keyboard. Throwup on your pillow need to chase tail. Stand in front of the computer screen rub face on everything yet why must they do that yet chase imaginary bugs but claw drapes, behind the couch. Intently stare at the same spot stick butt in face stand in front of the computer screen shake treat bag swat at dog. Hide when guests come over hide when guests come over. Chew foot hopped up on goofballs chase mice find something else more interesting need to chase tail so chase mice shake treat bag. Make muffins burrow under covers, hopped up on goofballs and burrow under covers nap all day leave dead animals as gifts. Attack feet chew iPad power cord, for intently stare at the same spot yet give attitude yet rub face on everything. Throwup on your pillow hide when guests come over or throwup on your pillow or destroy couch or hide when guests come over under the bed."
    msg.send "Throwup on your pillow. Sweet beast rub face on everything, and hide when guests come over intently stare at the same spot. Play time stick butt in face, for intently sniff hand hide when guests come over, so chase mice, yet chew iPad power cord for hunt anything that moves. Behind the couch make muffins but climb leg intently stare at the same spot. Chase mice hate dog. All of a sudden go crazy. Intently stare at the same spot cat snacks why must they do that. Behind the couch stare at ceiling, sun bathe but stretch hate dog behind the couch hunt anything that moves. Find something else more interesting mark territory chew foot cat snacks run in circles intently sniff hand. Flop over behind the couch sweet beast flop over. Inspect anything brought into the house hate dog yet nap all day or inspect anything brought into the house for throwup on your pillow use lap as chair. Sweet beast why must they do that for claw drapes or chase mice or need to chase tail. Sleep on keyboard intently sniff hand for lick butt but chase mice and sun bathe or run in circles yet chew foot. Stare at ceiling sun bathe yet need to chase tail or cat snacks and claw drapes. Under the bed play time yet swat at dog but give attitude, for nap all day. Leave dead animals as gifts. Run in circles. Missing until dinner time sweet beast run in circles, and chase mice, and hopped up on goofballs and stretch. Why must they do that chew foot hate dog flop over. Flop over. Chew foot. Give attitude intrigued by the shower, or intently sniff hand. Stick butt in face intently stare at the same spot or leave hair everywhere for why must they do that or lick butt. Use lap as chair hide when guests come over but intently sniff hand chase imaginary bugs or cat snacks. Sun bathe sleep on keyboard yet use lap as chair, rub face on everything, intently sniff hand but intrigued by the shower."
    msg.send "Sweet beast cat snacks leave hair everywhere under the bed, hide when guests come over stand in front of the computer screen. Burrow under covers. Hunt anything that moves behind the couch run in circles chase mice run in circles. Play time destroy couch or under the bed, leave hair everywhere. Chew foot need to chase tail or chase mice yet chew iPad power cord why must they do that. Why must they do that leave dead animals as gifts stick butt in face yet sleep on keyboard nap all day for chase mice. Throwup on your pillow hide when guests come over burrow under covers hate dog or why must they do that but hunt anything that moves. Sun bathe hide when guests come over. Hopped up on goofballs intrigued by the shower, missing until dinner time for intently stare at the same spot yet find something else more interesting, intently sniff hand chew foot. Give attitude sweet beast stare at ceiling but destroy couch. Throwup on your pillow run in circles throwup on your pillow missing until dinner time destroy couch. Chase mice leave hair everywhere so intently stare at the same spot and burrow under covers so claw drapes lick butt and chew iPad power cord. Nap all day missing until dinner time and leave dead animals as gifts. Chew iPad power cord hate dog sun bathe and sun bathe leave hair everywhere. Leave dead animals as gifts cat snacks. Cat snacks. Give attitude make muffins stare at ceiling so hopped up on goofballs. Sleep on keyboard."
    msg.send "Sleep on keyboard chew iPad power cord, and swat at dog but hunt anything that moves yet claw drapes. Intently sniff hand mark territory cat snacks for burrow under covers intrigued by the shower. Sweet beast. Chase mice leave dead animals as gifts chase mice hunt anything that moves but intently stare at the same spot. Chew iPad power cord find something else more interesting play time or chew iPad power cord sleep on keyboard or nap all day. Stare at ceiling. Stand in front of the computer screen give attitude and swat at dog, intently stare at the same spot need to chase tail use lap as chair. Attack feet make muffins chew foot but rub face on everything missing until dinner time, for chase imaginary bugs. Cat snacks. Hate dog missing until dinner time chase mice so destroy couch hunt anything that moves chew foot yet flop over. Hunt anything that moves under the bed. Sleep on keyboard missing until dinner time yet stick butt in face but chase mice so sun bathe or use lap as chair, for leave dead animals as gifts. Chase mice find something else more interesting and under the bed yet throwup on your pillow inspect anything brought into the house. Hopped up on goofballs lick butt, cat snacks hopped up on goofballs and find something else more interesting run in circles and mark territory. Flop over run in circles under the bed."
    msg.send "Chase imaginary bugs rub face on everything for run in circles. Why must they do that inspect anything brought into the house and run in circles but find something else more interesting intently stare at the same spot so shake treat bag so play time. Hunt anything that moves. Nap all day stare at ceiling hunt anything that moves and run in circles so give attitude. Why must they do that stretch but burrow under covers, so find something else more interesting and mark territory so shake treat bag so shake treat bag. Swat at dog. Sweet beast climb leg so attack feet but hopped up on goofballs. Run in circles nap all day and play time yet chew foot. Use lap as chair chew iPad power cord, so stretch. Sweet beast sun bathe so climb leg and give attitude chase mice. Mark territory stand in front of the computer screen yet rub face on everything for play time leave dead animals as gifts so cat snacks. Missing until dinner time claw drapes stick butt in face yet stand in front of the computer screen for sweet beast, so mark territory attack feet."
    msg.send "Intently stare at the same spot stretch intently stare at the same spot intently sniff hand or give attitude flop over. Sleep on keyboard run in circles why must they do that for leave hair everywhere. Burrow under covers claw drapes but claw drapes but chew iPad power cord so claw drapes. Leave hair everywhere throwup on your pillow but stand in front of the computer screen yet stretch but cat snacks flop over inspect anything brought into the house. Under the bed intrigued by the shower burrow under covers sun bathe. Stand in front of the computer screen need to chase tail. Sleep on keyboard. Why must they do that why must they do that. Leave dead animals as gifts shake treat bag. Claw drapes leave dead animals as gifts, and behind the couch mark territory. Throwup on your pillow attack feet for stare at ceiling for intently stare at the same spot. Stare at ceiling intrigued by the shower. Sleep on keyboard hunt anything that moves so intrigued by the shower all of a sudden go crazy run in circles. Intently stare at the same spot play time. Swat at dog claw drapes and all of a sudden go crazy find something else more interesting."