# Description
#   Floods the screen with lorem ipsum to hide NSFW content
#
# Dependencies:
#   None
#
# Configuration:
#   None
#
# Commands:
#   If it even hears NSFW it will scream
#
# Author:
#   Eric Lui

module.exports = (robot) ->
  robot.hear /NSFW/i, (msg) ->
    msg.send "All of a sudden go crazy missing until dinner time for hide when guests come over swat at dog, stand in front of the computer screen lick butt. Claw drapes. Lick butt lick butt for make muffins and intrigued by the shower so chew iPad power cord but chase mice make muffins. Give attitude leave dead animals as gifts play time behind the couch climb leg. All of a sudden go crazy play time. Leave dead animals as gifts find something else more interesting. Mark territory. Attack feet sleep on keyboard for climb leg. Inspect anything brought into the house run in circles claw drapes. Shake treat bag stretch so stand in front of the computer screen intrigued by the shower chew foot. Throwup on your pillow lick butt for climb leg. Sleep on keyboard nap all day but hate dog chase mice. Stand in front of the computer screen hate dog hopped up on goofballs or hunt anything that moves. Stare at ceiling cat snacks or destroy couch yet run in circles, stretch stand in front of the computer screen so sweet beast. Mark territory. Lick butt sun bathe. Chase imaginary bugs. Stick butt in face why must they do that. Intently stare at the same spot nap all day, stare at ceiling yet sweet beast mark territory. Destroy couch stand in front of the computer screen all of a sudden go crazy attack feet but find something else more interesting. Inspect anything brought into the house hunt anything that moves for stare at ceiling but stare at ceiling cat snacks but stand in front of the computer screen. Sleep on keyboard nap all day stare at ceiling but swat at dog for run in circles. Give attitude hate dog leave dead animals as gifts and give attitude. Destroy couch stare at ceiling and rub face on everything. Throwup on your pillow intently sniff hand for use lap as chair so swat at dog for intrigued by the shower intently sniff hand play time."
    msg.send ""
    msg.send "Under the bed under the bed missing until dinner time or find something else more interesting for rub face on everything. Stand in front of the computer screen attack feet but attack feet, so claw drapes flop over nap all day. Climb leg chase mice or chew iPad power cord so chew iPad power cord yet find something else more interesting claw drapes. Stand in front of the computer screen under the bed or hopped up on goofballs. Chew iPad power cord chew iPad power cord for need to chase tail or hide when guests come over. Chew foot why must they do that so play time. Intently stare at the same spot run in circles for use lap as chair for mark territory for chew foot swat at dog. Intently sniff hand run in circles use lap as chair so hopped up on goofballs. Destroy couch hide when guests come over." 
    msg.send ""
    msg.send "Inspect anything brought into the house mark territory stare at ceiling for climb leg. Why must they do that need to chase tail and destroy couch but nap all day run in circles. Chew iPad power cord claw drapes attack feet leave hair everywhere. Give attitude intrigued by the shower and find something else more interesting yet sleep on keyboard and intently stare at the same spot chew iPad power cord. Use lap as chair stick butt in face give attitude stick butt in face for run in circles. Hopped up on goofballs missing until dinner time hopped up on goofballs give attitude, but hate dog. Stretch sweet beast yet destroy couch sleep on keyboard shake treat bag chew foot. Run in circles throwup on your pillow or play time and rub face on everything attack feet chase mice mark territory. Use lap as chair flop over and stick butt in face. Leave hair everywhere destroy couch, or inspect anything brought into the house yet stretch leave hair everywhere but give attitude. Leave dead animals as gifts all of a sudden go crazy yet hide when guests come over. Stare at ceiling stand in front of the computer screen, for stick butt in face make muffins and rub face on everything. Run in circles sun bathe sleep on keyboard rub face on everything climb leg. Flop over inspect anything brought into the house. Leave hair everywhere missing until dinner time burrow under covers stick butt in face run in circles. Missing until dinner time chew foot hate dog play time yet mark territory, play time. Hate dog swat at dog for use lap as chair but play time. Shake treat bag rub face on everything or climb leg." 
    msg.send ""
    msg.send "Play time run in circles leave dead animals as gifts. Make muffins play time. Leave dead animals as gifts. Need to chase tail stare at ceiling climb leg yet use lap as chair and nap all day but attack feet. Why must they do that inspect anything brought into the house hide when guests come over but throwup on your pillow, hate dog. Mark territory play time or inspect anything brought into the house or flop over chew foot missing until dinner time. Intently sniff hand missing until dinner time flop over and chew iPad power cord yet use lap as chair run in circles. Chew iPad power cord attack feet play time rub face on everything or sun bathe for throwup on your pillow, and intrigued by the shower. Play time leave hair everywhere under the bed for intrigued by the shower. Claw drapes. Throwup on your pillow nap all day and swat at dog and give attitude swat at dog. Leave dead animals as gifts all of a sudden go crazy climb leg. Hide when guests come over nap all day, swat at dog but inspect anything brought into the house and behind the couch so why must they do that. Leave dead animals as gifts play time or shake treat bag, so use lap as chair but leave hair everywhere and throwup on your pillow behind the couch. Hate dog hate dog shake treat bag for sweet beast. Mark territory cat snacks yet hunt anything that moves leave dead animals as gifts need to chase tail. Throwup on your pillow hunt anything that moves sleep on keyboard yet use lap as chair or find something else more interesting. Hide when guests come over throwup on your pillow run in circles. Cat snacks stand in front of the computer screen yet hopped up on goofballs hunt anything that moves so intently sniff hand. Leave hair everywhere why must they do that, run in circles nap all day stand in front of the computer screen so swat at dog. Missing until dinner time burrow under covers or need to chase tail inspect anything brought into the house stick butt in face climb leg so attack feet." 
    msg.send ""
    msg.send "Intrigued by the shower burrow under covers play time or chew iPad power cord lick butt, yet burrow under covers why must they do that. Stare at ceiling hate dog. Intently sniff hand. Sun bathe cat snacks need to chase tail so inspect anything brought into the house hopped up on goofballs. Use lap as chair give attitude so shake treat bag. Make muffins. Make muffins hate dog, flop over but hide when guests come over. Stand in front of the computer screen. Hide when guests come over nap all day sun bathe rub face on everything under the bed. Leave hair everywhere. Swat at dog. Rub face on everything flop over or hopped up on goofballs. Play time missing until dinner time but swat at dog so swat at dog so stretch claw drapes and chew iPad power cord. Give attitude intently sniff hand chase mice yet make muffins chew foot mark territory. Stare at ceiling destroy couch or lick butt run in circles, hate dog, intrigued by the shower or stick butt in face. Find something else more interesting chew iPad power cord and destroy couch hate dog but chase imaginary bugs. Chew iPad power cord intrigued by the shower make muffins make muffins chase mice yet inspect anything brought into the house."
